# Site settings
title: Osagie Omigie
description: Computer Science
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br

# User settings
username: Osagie Omigie
user_description: Final Year Computer Science Student
user_title: Final Year Computer Science Student
email: osagieomigie@gmail.com
twitter_username: 
github_username:  osagieomigie
gplus_username:  

# Google-analytics
google-analytics:
  id: "UA-115124818-1"

exclude: ['package.json', 'src' , 'node_modules']
